version: "3.8"
services:
  server1:
    build:
      context: ./server1
      dockerfile: server1.Dockerfile
    networks:
      - network1
    environment:
    - SERVER_2=http://server2:8080
    ports:
      - "8081:8081"
  server2:
    build:
      context: ./server2
      dockerfile: server2.Dockerfile
    networks:
      - network1
    environment:
      - SERVER_1=http://server1:8081
    ports:
      - "8080:8082"
networks:
  network1:
