version: "3"

services:
  ORIG:
    depends_on:
      - messagequeue
    container_name: orig-container
    image: orig-image
    build:
      dockerfile: HttpServerORIG.dockerfile
      context: .
    environment:
      - connection='guest:guest@messagequeue:5672'
    networks:
      - backend
  IMED:
    depends_on:
      - messagequeue
    container_name: imed-container
    image: imed-image
    build:
      dockerfile: HttpServerIMED.dockerfile
      context: .
    environment:
      - connection='guest:guest@messagequeue:5672'
    networks:
      - backend
  OBSE:
    depends_on:
      - messagequeue
    container_name: obse-container
    image: obse-image
    build:
      dockerfile: HttpServerOBSE.dockerfile
      context: .
    environment:
      - connection='guest:guest@messagequeue:5672'
    networks:
     - backend
    volumes:
     - filestorage:/tmp/log.txt
  SERV:
    depends_on:
      - OBSE
      - IMED
      - ORIG
    container_name: httpserv-container
    image: httpserv-image
    build:
      dockerfile: HttpServ.dockerfile
      context: .
    networks:
      - backend
    ports:
      - 3333:3333
    volumes:
      - filestorage:/tmp/log.txt
  messagequeue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    networks:
      - backend

networks:
  backend:

volumes:
  filestorage:
